[package]
name = "g933-utils"
version = "0.1.0"
authors = ["Ash Levy <ashlea@protonmail.com>"]

[workspace]
members = ["libg933"]

[dependencies]
libg933 = { path = "libg933" }
clap = "2.29.1"
env_logger = "0.4.3"
failure = "0.1.1"
indoc = "0.2.3"
log = "0.3.9"
